### ISSUE TITLE
Container length not increasing with the increase in task count!

### ISSUE THREAD

**Issue by amarlearning** [sloria/simplist#1]
Length of the container is fixed due to which when the task count increases it overlaps with the footer content.
![screenshot from 2016-11-28 08-42-56](https://cloud.githubusercontent.com/assets/9383897/20655263/fcd14e72-b546-11e6-91d0-a3b2215ecdb0.png)

**Comment by sloria** [comment]
Thanks for reporting @amarlearning ! I'll try to look into that when I have time. PRs are always welcome =)

**Comment by sloria** [comment]
I deployed a workaround that will make the footer respond to the length of the container. Not the ideal solution, but certainly an improvement.

**Comment by amarlearning** [comment]
@sloria LGTM :+1: :100: 
I think it's time to close this PR!
